services:
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - clase4-mongo-data:/data/db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      MONGO_URL: mongodb://mongo:27017/clase4
    depends_on:
      - mongo

volumes:
  clase4-mongo-data:
