apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeusers
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubeusers
  template:
    metadata:
      labels:
        app: kubeusers
    spec:
      containers:
        - name: kubeusers
          image: kubeusers:local
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URL
              value: mongodb://mongo:27017/clase4
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: kubeservice
spec:
  type: LoadBalancer
  selector:
    app: kubeusers
  ports:
    - port: 80
      targetPort: 3000
